#ifndef _VNTCONSTANTS_H_
#define _VNTCONSTANTS_H_

#define VNT_NUM_JS_INPUTS 2
#define VNT_NUM_JS_OUTPUTS 2
#define INCREMENTAL_MERKLE_TREE_DEPTH 5
#define INCREMENTAL_MERKLE_TREE_DEPTH_TESTING 20

#define VNT_NOTEPLAINTEXT_LEADING 1
#define VNT_V_SIZE 8
#define VNT_RHO_SIZE 32
#define VNT_R_SIZE 32
#define VNT_MEMO_SIZE 128

#endif // _VNTCONSTANTS_H_
